const ActionTypes = {
  CALL_API: 'CALL_API',

  TOGGLE_LOGIN_STATUS: 'TOGGLE_LOGIN_STATUS',
  GET_VERSION_INFO_SUCCESS: 'GET_VERSION_INFO_SUCCESS',

  RELOATE_TO_CURRENT_PAGE: 'RELOATE_TO_CURRENT_PAGE',
};

export default ActionTypes;
